name: Publish Api and Frontend to GHCR

on:
  push:
    branches: ["main"]
env:
  IMAGE_NAME: ceffdptinfo/switch-manager-tool

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests
        run: |
          dotnet test "./Tests/APIxUnitTests/APIxUnitTests.csproj"
          dotnet test "./Tests/FrontendxUnitTest/FrontendxUnitTest.csproj"
      
      - name: Publish Api to Github Container Registry
        run: |
          dotnet publish "SwitchManagerTool/API/API.csproj" --os linux --arch x64 /t:PublishContainer -c Release \
            -p:ContainerRegistry=ghcr.io \
            -p:ContainerRepository=${{env.IMAGE_NAME}}-api \
            -p:ContainerRegistryUser=${{github.actor}} \
            -p:ContainerRegistryPassword=${{secrets.GITHUB_TOKEN}} \
            -p:ContainerImageTag=latest
            
      - name: Publish Frontend to Github Container Registry
        run: |
          dotnet publish "SwitchManagerTool/Frontend/Frontend.csproj" --os linux --arch x64 /t:PublishContainer -c Release \
            -p:ContainerRegistry=ghcr.io \
            -p:ContainerRepository=${{env.IMAGE_NAME}}-frontend \
            -p:ContainerRegistryUser=${{github.actor}} \
            -p:ContainerRegistryPassword=${{secrets.GITHUB_TOKEN}} \
            -p:ContainerImageTag=latest
